name=PedroRobot
version=1.0.2
author=TonNom
maintainer=TonNom <email@domain.com>
sentence=Library for controlling Pedro Robot with multiple modes (radio, bluetooth, playback, web).
paragraph=Provides a modular state machine and abstraction layers for buttons, display, servos, and radio modules.
category=Device Control
url=https://github.com/almtzr/PedroRobot
architectures=*
