name=PedroRobot
version=1.0.4
author=Almoutazar Saandi
maintainer=Almoutazar Saandi <contact@pedrobot.com>
sentence=Library for controlling Pedro Robot with multiple modes (radio, bluetooth, playback, web).
paragraph=Provides a modular state machine and abstraction layers for buttons, display, servos, and radio modules.
category=Robotics STEM
url=https://github.com/almtzr/Pedro
architectures=Microcontroller ATmega32u4
